### ISSUE TITLE
Replace username with name (user's full name)

### ISSUE THREAD

**Issue by rwakida** [sscpac/chat-locker#17]
****Update** scope expanded to replace username with name through the application. 

RocketChat displays the cryptic username instead of the user's name (full name) throughout the application.  Need to replace everywhere. 

When creating a channel/group, RocketChat searches using the username (e.g. bcleaver).  However, it searches using the name (e.g. Theodore Cleaver) when adding a member to an existing channel/group (editing). 

**Acceptance criteria:**

Channel:
- [x] Create Channel "Add members" input should search by 'name'
- [x] Create Channel added members should display 'name' field. 
- [x] Right tab (owner) - 'Add Users' input should search by 'name'
- Right tab (owner) - display 'name' of added members - **can't fix depends on #41**
- [x] Right tab (owner) - display 'name' of existing members
- [x] Right tab (owner) - display 'name' of existing member when viewing single user profile
- [x] Right tab (non-owner) - 'Quick Search' input should search by 'name' field
- [x] Right tab (non-owner) - display 'name' of existing members
- [x] Right tab (non-owner) - display 'name' of existing member when viewing single user profile

Direct message:
- [x] Create - "with whom" input should search by 'name'
- [x] Create - display 'name' in "with whom" input
- [x] Update - display 'name' in "with whom" input
- [x] SideNav - display 'name' for existing direct messages

Private group:
- [x] Create - "Members" input should search by 'name'
- [x] Create - display 'name' of added members 
- [x] Update - display 'name' of existing members
- [x] Update - "Members" input should search by 'name'
- [x] Update - display 'name' of added members
- [x] Right tab (owner) - 'Add Users' input should search by 'name'
- Right tab (owner) - display 'name' of added members - **can't fix depends on #41**
- [x] Right tab (owner) - display 'name' of existing members
- [x] Right tab (owner) - display 'name' of existing member when viewing single user profile
- [x] Right tab (non-owner) - display 'name' of existing members
- [x] Right tab (non-owner) - display 'name' of existing member when viewing single user profile

User Status:
- [x] SideNav at the top - display 'name' of currently logged in user

Messages:
- [x] Replace "Room_name_changed" system message
- [x] Replace "User_added_by" system message
- [x] Replace "User_removed_by" system message
- [x] Replace "User_left" system message
- [x] Replace "User_added" system message
- [x] Replace "User_joined_channel" system message
- [x] Replace "Welcome" system message
- [x] Conversation - display 'name' of message sender

User typing:
- [x] Bottom of room - display 'name' of member typing.  Appears to other room members WHILE in the room.

**Comment by douglasrapp** [comment]
To add to the inconsistency, using the search box in the right-hand pane differs in behavior between channels and groups. While in a group, that box is used to search for users and add them to the group. While in a channel, the box is used to search for users and then start direct messages with them.

EDIT: Turns out this isn't entirely correct... With channels, the owner/creator of the channel can use the right-pane search box to add users. Everyone else can only search for users and initiate direct messages with them. With private groups, the owner/creator can add users like with channels. Other members don't even get the search box.

Still kind of inconsistent.

**Comment by douglasrapp** [comment]
I think in all cases, we should be keying off of and displaying full names. I don't think users should be expected to know any usernames other than their own.

**Comment by bbrockman** [comment]
I agree.

**Comment by bbrockman** [comment]
just had to note the excellent use of checkboxes :smiley:
