### ISSUE TITLE
CRUD contact list (backend)

### ISSUE THREAD

**Issue by rwakida** [sscpac/chat-locker#22]

**Comment by berkich** [comment]
Should we create a new Contacts collection or put the contacts in the user's profile

**Comment by bbrockman** [comment]
I think those would be best in their own collection.

**Comment by berkich** [comment]
That was my initial thought and the route I was going. Just wanted to
confirm

**Comment by bbrockman** [comment]
I think we need to have a contacts and a chat_groups.  From the front end, I need to have a call (publication) to get the groups with its contacts, add a group, remove a group, rename a group, add a contact to group, remove a contact from a group.

What am I missing?

**Comment by berkich** [comment]
I have been working on most of that except the rename (easy to do). I was
working on logic for private and public chat groups, but just getting
started with that.
I was going to have a list of userIds in the chat groups and then the front
end could get the "userData" details using that list

**Comment by rwakida** [comment]
- I think of a "chat group" as a "contact list".  
- The point of a contact list is to 
  - quickly see user status for the people I'm interested in
  - quickly communicate with one or more people on the list
- For simplicity, I think we should only have 1 private contact list per user.  It serves as a favorite and allows the user to quickly see who is online.  Having more then 1 list will complicate the UI and duplicates existing functionality.  
  - a channel is basically a public list. 
  - a private group is a private list
  - we can send a message to everyone on channel or private group using "@all" (existing functionality)
- I think we should make it easy to add users to the favorite contact list.  
- I think we should make it easier to add users to a private group/channel by enhancing the "add user" search field.  e.g. instead of searching by only name, we can search by location and add all users for that result.

**Comment by berkich** [comment]
I was thinking about and researching this. There is definitely redundancy
with chat groups and contact list groups
