### ISSUE TITLE
Implement custom status message

### ISSUE THREAD

**Issue by bbrockman** [sscpac/chat-locker#26]
Acceptance Criteria:
- [x] Add Custom message to user slide in box
- [x] Add ability to assign a custom message 
- [x] Add ability to view a users custom message (user detail box)

**Comment by rwakida** [comment]
After reviewing Brent's change for sscpac/chat-locker#42, I realized this is not trivial.  If they can create their own custom status, what color do we display?

**Comment by bbrockman** [comment]
Status would be status still. Message would be additional field.

**Comment by rwakida** [comment]
Sorry, maybe I misunderstood the task.  Is this adding a new status like "out for lunch" that would be a choice similar to how we select online, away, busy status message?

**Comment by bbrockman** [comment]
Yes, but it is in addition to status.
