### ISSUE TITLE
New direct message overwrites existing direct message access permissions

### ISSUE THREAD

**Issue by rwakida** [sscpac/chat-locker#43]
To Replicate:
1. User 1 creates DM with user 2.  Specify 'S' classification.  DM should appear under direct messages section.
2. Click on created DM and verify 'S' classification. 
3. User 1 creates DM with user 2.  Specify 'U' classification.  A new DM should NOT be created. 
4. Click on the DM from step 1.  Verify 'U' is now set.  

RocketChat uses the members usernames for the room _id. Thus, we can never create a new DM when there's an existing DM.  Worse yet, the create logic doesn't check for an existing room and calls upsert that updates an existing room.  Thus, the old permissions are overwritten.

**Comment by rwakida** [comment]
Depends on #27

**Comment by bbrockman** [comment]
Should be fixed with #68

**Comment by douglasrapp** [comment]
Fixed with issue #68
