### ISSUE TITLE
Want to join the main development team?

### ISSUE THREAD

**Issue by engelgabriel** [sscpac/chat-locker#45]
We guys seem very active and developing some very important features we have been missing on the Rocket.Chat main project. We'd love to have you guys on the team, or at least help you push more PRs to the main project to keep them more in sync :)

**Comment by bbrockman** [comment]
It would be great to work together. If they are shared features, we'd love to push them your way.  One of our big new features will be a contact list pulled from ldap. Have you guys thought much about that? We're deciding now where the best place to put it would be. Hard to decide since there is already flex panels on the right and left. Please feel free to comment on any features we have. We would appreciate your opinions. We hope to create docker containers for development for ldap and meteor.

**Comment by engelgabriel** [comment]
Cool, thats one of the most wanted features in our Roadmap. We have a Federal University in Brazil that wants to deploy the chat for 40k students.. and they need to load the users form their LDAP server.

Lets work on this together!!!

We should add this to the LDAP package. It already does the authentication using ldap domain.

Is there a webhook on your ldap server to push changes? Or should the chat server pool periodically for changes and diff? In that case, is there a update timestamp to narrow the query?

**Comment by engelgabriel** [comment]
I'll ask the other contributors to do a pull request from your branch and see what can we merge back to our master. We can all work together to resolve conflicts and get the source code synced again. Our idea is that you should be able to add ANY feature using the packages APIs.

So in the ideal scenario,  your fork would be EXACTLY like our master,  and you'd have some extra folders inside /packages/ with your EXTRA features.

If you join the core development team, you can help us create the APIs that are missing to allow you to do that.

**Comment by engelgabriel** [comment]
The original issue at our project https://github.com/RocketChat/Rocket.Chat/issues/232

**Comment by engelgabriel** [comment]
On my first look, lots of the changes can be turned into SETTINGS, and another big part, the Access Permissions, is something we would love to add to the main project.

**Comment by engelgabriel** [comment]
Hi @bbrockman did you give on this?

**Comment by bbrockman** [comment]
Hello @engelgabriel!  Not really.  We were in charge of doing a 'prototype'.  We have completed as far as we will go with the prototype, but it is likely that there will be additional development in the future.  I appreciate all the work you guys have put into this and wish you the best of luck!  I'm sorry we had such a quick turnaround to complete our prototype and weren't able to integrate together more.  Maybe another time.

**Comment by engelgabriel** [comment]
Thats ok! I presume you did see what @rwakida merge back into our code? The roles and permissions.

**Comment by bbrockman** [comment]
I did.  @rwakida is awesome.

**Comment by engelgabriel** [comment]
I can't agree more! @rwakida is awesome indeed! Does this change make it easier for you guys to keep in sync?
