### ISSUE TITLE
Need to set Avatar when importing LDAP users

### ISSUE THREAD

**Issue by rwakida** [sscpac/chat-locker#52]
Need to specify an Avatar when importing users from LDAP. 
1. browser request is refused with ERR_CONNECTION_REFUSED when retrieving Avatar.
2. UI alignment looks weird.  For example direct message right flex tab, username is offset to the right because UI expects an Avatar, but none is displayed

**Comment by bbrockman** [comment]
Is there a way to automatically set to use the initials?

**Comment by rwakida** [comment]
Not a bug.  The URL path to avatar service was incorrect because ROOT_URL was not specified and defaulted to localhost:3000 (I'm running in Virtual Machine accessible from static IP).  I had to export ROOT_URL=http://<ip>:3000 before running meteor.

This should not be a problem in production because "meteor deploy" sets it for us (per [meteor docs](http://docs.meteor.com/#/full/meteor_absoluteurl))
