### ISSUE TITLE
Indicate room creator/owner in member list

### ISSUE THREAD

**Issue by rwakida** [sscpac/chat-locker#54]
It would be nice to see who is the creator/owner of the room in the member list.

**Comment by berkich** [comment]
Cannot determine the owner/creator of a direct room

**Comment by douglasrapp** [comment]
I _think_ the owner of a direct message is implied by the order of the usernames making up the room id. So if the id is "testuser1testuser2", then testuser1 is the owner.

**Comment by rwakida** [comment]
you're right about the id format, but I wonder if a direct message really has an "owner".

**Comment by bbrockman** [comment]
But I think that should be the slug and I'd should be a real id so we can have multiple conversations with multiple classifications.

**Comment by bbrockman** [comment]
Of course we could always populate an owner field 😀

**Comment by douglasrapp** [comment]
Nope, I lied. When the direct message is created, the two usernames are first sorted then joined to make up the room id. The first one listed isn't the creator, it's just the one that comes first alphabetically ;).

I think Reid has a point - should there even be an 'owner' for a direct message? Maybe if we want to use that as criteria for deleting it (a la issue #20).

**Comment by bbrockman** [comment]
That brings up a good point. If Doug deletes a conversation I have with me in a direct message, I would want to keep my copy!
