### ISSUE TITLE
Possible regression: when (re)labeling a conversation, users not getting styled for conflicts

### ISSUE THREAD

**Issue by douglasrapp** [sscpac/chat-locker#62]
When labeling or relabeling a direct message or private group, potential/selected users are not getting highlighted when there is a security label conflict under 2 situations:

1) When typing in the auto-complete box to add a user, the entries in the drop-down list of users to select are never styled, even when some of those users do not have access to current labels.

2) In a private group, when a user is selected and their corresponding "chiclet" entry appears underneath the input box, that "chiclet" is never styled, even if security labels are selected that cause a conflict.

In both cases, the relevant security labels still get styled, and the pertinent warnings still get displayed as expected.

I believe this is a regression (pretty sure this was working earlier), and possibly caused by the change from displaying usernames to displaying full names. It is possible that the security label code is operating on usernames, while the drop-down/chiclet fields are only including full name data, and so they never match.

**Comment by bbrockman** [comment]
That was working before.

**Comment by douglasrapp** [comment]
Created branch bugfix/chat-locker-62

**Comment by rwakida** [comment]
:+1:

**Comment by douglasrapp** [comment]
Merged branch (pull request #66).
