### ISSUE TITLE
Editing target user field without selecting from drop-down does not update anything

### ISSUE THREAD

**Issue by douglasrapp** [sscpac/chat-locker#64]
Related to #63.

When creating a direct message, any updates to the 'with whom' field that don't involve selecting an entry from the drop-down dialog do not stick.

Steps to reproduce:
1. Create a direct message
2. In the 'with whom' dialog, select any user
3. Now, put the cursor in the 'with whom' dialog and make a small modification (e.g., hit backspace to remove a few letters from the name)
4. Hit the 'Save' button - a new direct message is created with the user selected in step (2), rather than the value set in step (3)

Expected behavior:
A direct message should be created with exactly the text that appears in the 'with whom' field, so as to not be confusing to the user. In the case that the input text does not correspond to an actual user in the system, and error should be returned.

**Comment by bbrockman** [comment]
I don't agree.  The message should be started with the person who you added the chicklet for.

**Comment by douglasrapp** [comment]
But in the case of a direct message, there is no chiclet. There's only a line with a name on it. Maybe one fix is to add a chiclet, and enforce that there be only one (since it's a DM).

**Comment by bbrockman** [comment]
I see.  That isn't good.

**Comment by douglasrapp** [comment]
Created branch bugfix/chat-locker-64

**Comment by douglasrapp** [comment]
Created pull request #100

**Comment by douglasrapp** [comment]
Branch merged
