### ISSUE TITLE
Update settings to use RocketChat's settings and add admin username setting

### ISSUE THREAD

**Issue by rwakida** [sscpac/chat-locker#73]
Does our LDAP datastore specify an admin field?  We can't create a local user like RocketChat does (see initialData) because we authenticate against LDAP and the user doesn't exist in LDAP.  

The other option is to specify a LDAP username in default settings similar to our LDAP configuration.

**Comment by bbrockman** [comment]
I think for now it would be best to specify an LDAP username in the default settings.
